networks:
  core_proxy:
    external: true

services:
  ai:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data_user/:/user_data/
      - ./data/:/data/
      - ./xaelai/:/app/xaelai  # Mount the xaelai directory to /app/xaelai in the container
    env_file: ".env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xaelai.rule=Host(`xaelai.outsidecontext.solutions`)"
      - "traefik.http.routers.xaelai.entrypoints=websecure"
      - traefik.http.services.xaelai.loadbalancer.server.port=8501
      - "traefik.http.routers.xaelai.tls.certresolver=letsencrypt"
      - traefik.http.routers.xaelai.middlewares=ldap_auth
      # ldapAuth Options=================================================================
      - traefik.http.middlewares.ldap_auth.plugin.ldapAuth.enabled=true
      - traefik.http.middlewares.ldap_auth.plugin.ldapAuth.url=ldap://lldap
      - traefik.http.middlewares.ldap_auth.plugin.ldapAuth.port=3890
      - traefik.http.middlewares.ldap_auth.plugin.ldapAuth.baseDN=ou=people,dc=outsidecontext,dc=solutions
      - traefik.http.middlewares.ldap_auth.plugin.ldapAuth.attribute=uid
    networks:
      - core_proxy
      - default

  pgvector:
    image: phidata/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data_pgvector:/var/lib/postgresql/data
    # ports:
    #   - "5532:5432"
  ollama:
    image: ollama/ollama:latest
    # ports:
    #   - 7869:11434
    volumes:
      - ./data_ollama/:/root/.ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Limit to 1 CPU
          memory: 512M  # Limit to 512MB of memory
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
